### ISSUE TITLE
Postgres 12.1 Compatibility

### ISSUE THREAD

**Issue by andrewclink** [on-site/active_record-postgres-constraints#21]
Using rails, with `rails db:schema:dump` on Postgresql 12.1 my `schema.rb` file is full lines like the following:

``` SQL
# Could not dump table "add_ons" because of following ActiveRecord::StatementInvalid
#   PG::UndefinedColumn: ERROR:  column "consrc" does not exist
LINE 1: SELECT conname, consrc FROM pg_constraint JOIN pg_class ON p...
                        ^
HINT:  Perhaps you meant to reference the column "pg_constraint.conkey" or the column "pg_constraint.conbin".
: SELECT conname, consrc FROM pg_constraint JOIN pg_class ON pg_constraint.conrelid = pg_class.oid WHERE pg_constraint.contype = 'c' AND pg_class.relname = 'add_ons'

```

**Comment by bibendi** [comment]
`consrc` was removed since Postgres 12.

Also, note, `consrc` is not updated when referenced objects change; for example, it won't track renaming of columns. Rather than relying on this field, it's best to use `pg_get_constraintdef()` to extract the definition of a check constraint.

https://github.com/on-site/active_record-postgres-constraints/blob/b80ab62bf2d6147d96a699eef626cdfa1d6e27c5/lib/active_record/postgres/constraints/postgresql_adapter.rb#L31

https://github.com/on-site/active_record-postgres-constraints/blob/b80ab62bf2d6147d96a699eef626cdfa1d6e27c5/lib/active_record/postgres/constraints/types/check.rb#L17

**Comment by betesh** [comment]
PR welcome.  You may want to try some of the suggestions in https://github.com/travis-ci/travis-ci/issues/954 to ensure we are testing with a range of postgresql versions.

**Comment by bibendi** [comment]
> PR welcome.

Well, it would be odd to hear otherwise. :slightly_smiling_face: 

Unfortunately, I didn't use this gem before and only googled a similar functionality today. So, I'd rather wait until a maintainer fixes the bug :wink:

**Comment by andrewclink** [comment]
Fixed in PR #22. Open to feedback.

**Comment by betesh** [comment]
Closing in favor of #22

**Comment by ziaulrehman40** [comment]
Until a solution is merged, issues should not be closed just because there is a PR, i opened a new issue #27  thinking there is no open issue for this thing.
Closing my issue, nvm.

**Comment by betesh** [comment]
> Until a solution is merged, issues should not be closed just because there is a PR

@ziaulrehman40 Perhaps you're right about that.  For my own education, I'd like to know whether that's an expectation most github users have.  I've seen some work that way, but I've also seen plenty work the other way.  Do you mind sharing some examples or articles that discuss this?

**Comment by ziaulrehman40** [comment]
Well, @betesh its better to reduce confusion IMO, there is no standard in here just convenience and clarity for users. If we take ISSUE word literally as well it implies issue should not be closed until a solution is merged. Because a solution can take many PRs but if issue is closed before any PR is finalized, no one can come and pick the issue from where it is. He has to scan PR pages separately and go from there.
Just my opinion of-course.

**Comment by betesh** [comment]
> Because a solution can take many PRs but if issue is closed before any PR is finalized, no one can come and pick the issue from where it is. He has to scan PR pages separately and go from there.

Very good point, I'll keep it in mind going forward.
